#!/usr/bin/env node
// Exports contract ABIs from Foundry build artifacts into packages/contracts-abi.
//
//   forge build && node script/export-abi.mjs
//
// Writes  packages/contracts-abi/abis.ts        (arenaAbi, brokerMonAbi, syntheticStockAbi, `as const`)
// Copies  contracts/deployments/10143.json  ->  packages/contracts-abi/deployments.json   (if it exists)
// Creates a placeholder deployments.json if none exists yet. index.ts is hand-maintained and never overwritten.

import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const contractsDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outPkgDir = resolve(contractsDir, "..", "packages", "contracts-abi");

/** [Solidity contract name, exported const name] */
const EXPORTS = [
  ["BattleArena", "arenaAbi"],
  ["BrokerMonNFT", "brokerMonAbi"],
  ["SyntheticStock", "syntheticStockAbi"],
];

const CHAIN_ID = 10143;
const PLACEHOLDER = { chainId: CHAIN_ID, arena: null, brokerMon: null, tokens: {} };

function loadAbi(name) {
  const artifact = join(contractsDir, "out", `${name}.sol`, `${name}.json`);
  if (!existsSync(artifact)) {
    throw new Error(`Missing artifact ${artifact}. Run \`forge build\` in contracts/ first.`);
  }
  const { abi } = JSON.parse(readFileSync(artifact, "utf8"));
  if (!Array.isArray(abi) || abi.length === 0) throw new Error(`Empty ABI in ${artifact}`);
  return abi;
}

mkdirSync(outPkgDir, { recursive: true });

let ts =
  "// AUTO-GENERATED by contracts/script/export-abi.mjs from Foundry build artifacts. DO NOT EDIT.\n" +
  "// Regenerate: cd contracts && forge build && node script/export-abi.mjs\n\n";
for (const [name, constName] of EXPORTS) {
  ts += `export const ${constName} = ${JSON.stringify(loadAbi(name), null, 2)} as const;\n\n`;
}
writeFileSync(join(outPkgDir, "abis.ts"), ts.trimEnd() + "\n");
console.log(`wrote ${join(outPkgDir, "abis.ts")}`);

const deployed = join(contractsDir, "deployments", `${CHAIN_ID}.json`);
const target = join(outPkgDir, "deployments.json");
if (existsSync(deployed)) {
  copyFileSync(deployed, target);
  console.log(`copied ${deployed} -> ${target}`);
} else if (!existsSync(target)) {
  writeFileSync(target, JSON.stringify(PLACEHOLDER, null, 2) + "\n");
  console.log(`wrote placeholder ${target}`);
} else {
  console.log(`no ${deployed}; kept existing ${target}`);
}
